### ISSUE TITLE
Long-term purpose, already existing package?

### ISSUE THREAD

**Issue by AkenRoberts** [antonioribeiro/ia-collection#2]
Antonio, saw you created this package on my GitHub feed. I know that others have done the same extraction of Laravel's Collections already, specifically [TightenCo](https://github.com/tightenco/collect).

Just curious if your fork intends to be different in any way, thus providing a reason to choose yours over an alternative.

Cheers 😄

**Comment by antonioribeiro** [comment]
I started by TightenCo's, I loved it so much that I build a package (kind of) extending it, and even coded an upgrader to download the last version and change the namespace from Illuminate to Tightenco: https://github.com/antonioribeiro/coollection/blob/d1cd6d9198f68b05e69b97e635ccf78949711b04/upgrade-collect.sh#L15. So it was, actually, a very difficult decision, which I had to make because:

1) To use [this package](https://github.com/antonioribeiro/coollection) in my Laravel projects and packages, I needed the extracted collection to have a different namespace, but  TightenCo's namespace is still conflicting with Laravel's. To stop hacking it, I made this PR waiting to change that there: https://github.com/tightenco/collect/pull/68. So I was basically using, instead of an extension, the extraction of the extraction, and it started to become cumbersome, or too hacky.

2) I started to need **Str** and **Arr** also separated from Laravel's, so I extracted them from Illuminate and created those two other packages using the same namespace (IlluminateAgnostic):  

- https://github.com/antonioribeiro/ia-arr
- https://github.com/antonioribeiro/ia-str

3) In the process of coding the upgrader script for Collect, I saw some tests (and at the time some other classes or interfaces) have been left behind, this version has them all.

4) Updates on TightenCo are a little slow lately, Matt his crew must be overwhelmed there, but I will never blame them, OSS is hard. So I also plan to make the update to be (kind of) automatic, using webhooks. Unless, of course, the tests fail, for that we really need to have all tests (related to the extraction) in place. 

5) I wrote some more tests to push the main class (not the whole code yet) to 100% test coverage, only need to help us detect possible changes not covered by tests and other missing files (traits, interfaces).

6) If I have time, I plan to extract some other classes/services from Laravel, already tried to extract Cache, because I was forced to use the Nette's one in [this package](https://github.com/antonioribeiro/countries), and it is already using **Coollect**, which extends **ia-collection**, but Cache, and I was able to reach 98% of the extraction unti I bumped into it accessing the `app()` helper, so like most Laravel stuff, it is too tightly tied to Laravel's infrastructure and I had to stop, at least for now.

But I'm not totally sold on this yet, I like the idea of an extraction but I really think Laravel should make those subpackages agnostic, so we could just use them, and I also vote in favor of the TightenCo's version.

**Comment by mattstauffer** [comment]
Hey folks! Thanks @antonioribeiro for pointing this conversation out to me. Quick responses:

1. I'm hopefully reviewing the PR for a new namespace today--here goes nothing!
2. Yah, we're not going to touch str and arr. 👌 
3. I don't know what's missing; I know when you first built your upgrader, it was on a day where a new release had come out so your upgrader identified a few dozen files that were promptly released that day when @besologic, who's doing the upgrades manually, pushed out that day's upgrade. Any other issues other than those that popped up that day?
4. Yep. Guilty as charged. Thankfully I'm makign time today, so hopefully we'll get there soon.
5. Yah, we're definitely not *planning* to add tests that don't exist in the existing codebase, so anyone who feels the need for that could certainly decide to build their own tooling.
6. Not sure I 100% follow this.

Thanks for continuing to vote in our favor! I think my next steps are to review and merge our outstanding PRs and then we can take a look then.

<3

**Comment by cryode** [comment]
Has there been any specific reason or rationale given why Laravel itself cannot split Collections out? I've searched around and haven't found anything directly from Taylor and crew. Perhaps I'm just not familiar enough with the scope in doing so.

Seems like a lot of work to get automated extractions going, when less effort could be spent separating the source.

**Comment by mattstauffer** [comment]
@cryode It's more work than you would think. I actually started Collect as a PR to the core, but it has so much inter-connection with other aspects of Illuminate that it quickly became untenable, which is when I got Taylor's blessing to split out Collect.

**Comment by cryode** [comment]
I can see how it turns into a rabbit hole really quickly. (Where do `Arr` and `Str` go? Illuminate contracts?)

I also disagree with things like debug tools such as `dump()` being attached to it by default.

(shrug) The architect in me wants to find at least a starting point that can be PR'ed to at least move towards an eventual Collections split, but I'll trust you guys have done enough diligence in figuring out what's worth the effort and what's not.

**Comment by antonioribeiro** [comment]
The main problem splitting Illuminate stuff is that things are bound together and are sharing the same classes/interfaces, the perfect world (or nightmare) would be most of those classes and helpers split in thousands of different packages and tiny helper files. Se we could just ditch `dd()` if we don't like it. 

For instance, Macroable would have to be a different package, because it is all around, but even inside the Laravel source code it's not unanimous, I see the `__call()` method been renamed in several places:

![image](https://user-images.githubusercontent.com/3182864/35643737-4ff7110e-06ae-11e8-934c-477ef5f46133.png)

Because sometimes we really need magic. Collection is using Str and Arr, which is also using Collection. While splitting them into packages I just decided to copy all those (needed) classes to each one, with their on namespaces (IlluminateAgnostic\Arr, for instance). Far from being the perfect world, but allows full emancipation without compromising core features.

**Comment by cryode** [comment]
Are things like Macros, Contracts, etc. actually useful in the Collection class outside of Laravel? Or are your projects making use of `sortBy()` and whatnot?

Perhaps we can separate the core agnostic Collection functionality into a new namespace, and have `Illuminate\Support\Collection` wrap it with the Laravel traits and contracts. The biggest change I can see right now is `Arr` would look for the agnostic collection instead of the magic-filled one, which may introduce a rare BC issue.

**Comment by AkenRoberts** [comment]
New progress and other discussions happening in laravel/framework#25421, so I'll close this. Thank you Antonio and Matt!

**Comment by mathieutu** [comment]
@antonioribeiro @mattstauffer @AkenRoberts  I'm just seeing this conversation, and I agree with all of you 😅.
After discussing with @taylorotwell I've opened a new PR, but the macroable is indeed in the center of questions. Please feel free to comment and help in the PR, I'm sure you will be really relevant with all the work you did around externalizing collections.

Thanks!
